import { Metadata } from "next";

export const metadata:Metadata = {
  title: {
    default:"Next.js - Dev&IT",
    absolute:"",
    template:"%s | Dev&IT"
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body>
        <header>
          <p
            style={{
              backgroundColor: "lightblue",
              fontWeight: "bold",
              height:"100px",
              padding:"5px"
            }}
          >
            Header
          </p>
        </header>
        {children}
        <footer>
          <p
            style={{
              backgroundColor: "lightcyan",
              fontWeight: "bold",
              height:"100px",
              padding:"5px"
            }}
          >
            Footer
          </p>
        </footer>
      </body>
    </html>
  );
}
