import { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: {
    default: "Next.js - Dev&IT",
    absolute: "",
    template: "%s | Dev&IT",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body>
        <header className=" text-center my-3 mx-3 p-4 bg-blue-600 uppercase rounded-lg hover:bg-blue-800 text-white">
          <h2 className=" font-bold text-2xl">Header</h2>
        </header>
        <div className=" h-[74vh]">
        {children}
        </div>
        <footer className=" text-center my-3 mx-3 p-4 bg-indigo-600 rounded-lg uppercase hover:bg-indigo-800 text-white">
          <h2 className=" font-bold text-2xl">Footer</h2>
        </footer>
      </body>
    </html>
  );
}
